### ISSUE TITLE
Exercise 37: Using External Variables ("external_variables") ("Chapter 4.3")

### ISSUE THREAD

**Issue by danwritecode** [danwritecode/clings#110]
Looking for help creating exercise:
Topic: **Using External Variables**
Exercise Directory Name: **external_variables**

Note: For Directory Name, refer to the exercises directory to find the correct number to use. It should be close to the number in the issue title but may be slightly off.

Refer to "The C Programming Language" book, Chapter 4.3 for more information.

Contribution instructions: https://github.com/danwritecode/clings?tab=readme-ov-file#contributions

**Comment by sleaper** [comment]
I will take the whole chapter 4

**Comment by danwritecode** [comment]
sounds good @sleaper...fyi, I'm in the middle of a product launch for the product I'm working on. will try to get some clings exercises done soon. just wanted to update you on what i'm currently focused on
