### ISSUE TITLE
Exercise 22: Increment and Decrement Operators ("inc_dec_operators") ("Chapter 2.8")

### ISSUE THREAD

**Issue by danwritecode** [danwritecode/clings#125]
Looking for help creating exercise:
Topic: **Increment and Decrement Operators**
Exercise Directory Name: **inc_dec_operators**

Note: For Directory Name, refer to the exercises directory to find the correct number to use. It should be close to the number in the issue title but may be slightly off.

Refer to "The C Programming Language" book, Chapter 2.8 for more information.

Contribution instructions: https://github.com/danwritecode/clings?tab=readme-ov-file#contributions

**Comment by sleaper** [comment]
I will take the whole chapter 2
