### ISSUE TITLE
Exercise 21: Type Conversions in C ("type_conversions") ("Chapter 2.7")

### ISSUE THREAD

**Issue by danwritecode** [danwritecode/clings#126]
Looking for help creating exercise:
Topic: **Type Conversions in C**
Exercise Directory Name: **type_conversions**

Note: For Directory Name, refer to the exercises directory to find the correct number to use. It should be close to the number in the issue title but may be slightly off.

Refer to "The C Programming Language" book, Chapter 2.7 for more information.

Contribution instructions: https://github.com/danwritecode/clings?tab=readme-ov-file#contributions

**Comment by sleaper** [comment]
I will take this one
