### ISSUE TITLE
Exercise 19: Arithmetic Operators in C ("arithmetic_operators") ("Chapter 2.5")

### ISSUE THREAD

**Issue by danwritecode** [danwritecode/clings#128]
Looking for help creating exercise:
Topic: **Arithmetic Operators in C**
Exercise Directory Name: **arithmetic_operators**

Note: For Directory Name, refer to the exercises directory to find the correct number to use. It should be close to the number in the issue title but may be slightly off.

Refer to "The C Programming Language" book, Chapter 2.5 for more information.

Contribution instructions: https://github.com/danwritecode/clings?tab=readme-ov-file#contributions

**Comment by sleaper** [comment]
I will take this one
