### ISSUE TITLE
Exercise 18: Declarations in C ("declarations") ("Chapter 2.4")

### ISSUE THREAD

**Issue by danwritecode** [danwritecode/clings#129]
Looking for help creating exercise:
Topic: **Declarations in C**
Exercise Directory Name: **declarations**

Note: For Directory Name, refer to the exercises directory to find the correct number to use. It should be close to the number in the issue title but may be slightly off.

Refer to "The C Programming Language" book, Chapter 2.4 for more information.

Contribution instructions: https://github.com/danwritecode/clings?tab=readme-ov-file#contributions

**Comment by sleaper** [comment]
I will take this one
