### ISSUE TITLE
Exercise 16: Data Types and Sizes in C ("data_types") ("Chapter 2.2")

### ISSUE THREAD

**Issue by danwritecode** [danwritecode/clings#131]
Looking for help creating exercise:
Topic: **Data Types and Sizes in C**
Exercise Directory Name: **data_types**

Note: For Directory Name, refer to the exercises directory to find the correct number to use. It should be close to the number in the issue title but may be slightly off.

Refer to "The C Programming Language" book, Chapter 2.2 for more information.

Contribution instructions: https://github.com/danwritecode/clings?tab=readme-ov-file#contributions

**Comment by sleaper** [comment]
Can I take this one?

**Comment by danwritecode** [comment]
go for it! just assigned you.
