### ISSUE TITLE
Exercise 3: The for Statement ("for_statement") ("Chapter 1.3")

### ISSUE THREAD

**Issue by danwritecode** [danwritecode/clings#144]
Looking for help creating exercise:
Topic: **The for Statement**
Exercise Directory Name: **for_statement**

Note: For Directory Name, refer to the exercises directory to find the correct number to use. It should be close to the number in the issue title but may be slightly off.

Refer to "The C Programming Language" book, Chapter 1.3 for more information.

Contribution instructions: https://github.com/danwritecode/clings?tab=readme-ov-file#contributions

**Comment by 7etsuo** [comment]
Can you assign me to each of these. (all of ch1). 

https://github.com/danwritecode/clings/issues/144 [help wanted](https://github.com/danwritecode/clings/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22)
#144 opened 2 days ago by [danwritecode](https://github.com/danwritecode/clings/issues?q=is%3Aissue+is%3Aopen+author%3Adanwritecode)
https://github.com/danwritecode/clings/issues/143 [help wanted](https://github.com/danwritecode/clings/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22)
#143 opened 2 days ago by [danwritecode](https://github.com/danwritecode/clings/issues?q=is%3Aissue+is%3Aopen+author%3Adanwritecode)
https://github.com/danwritecode/clings/issues/142 [help wanted](https://github.com/danwritecode/clings/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22)
#142 opened 2 days ago by [danwritecode](https://github.com/danwritecode/clings/issues?q=is%3Aissue+is%3Aopen+author%3Adanwritecode)
https://github.com/danwritecode/clings/issues/141 [help wanted](https://github.com/danwritecode/clings/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22)
#141 opened 2 days ago by [danwritecode](https://github.com/danwritecode/clings/issues?q=is%3Aissue+is%3Aopen+author%3Adanwritecode)
https://github.com/danwritecode/clings/issues/140 [help wanted](https://github.com/danwritecode/clings/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22)
#140 opened 2 days ago by [danwritecode](https://github.com/danwritecode/clings/issues?q=is%3Aissue+is%3Aopen+author%3Adanwritecode)
https://github.com/danwritecode/clings/issues/139 [help wanted](https://github.com/danwritecode/clings/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22)
#139 opened 2 days ago by [danwritecode](https://github.com/danwritecode/clings/issues?q=is%3Aissue+is%3Aopen+author%3Adanwritecode)
https://github.com/danwritecode/clings/issues/138 [help wanted](https://github.com/danwritecode/clings/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22)
#138 opened 2 days ago by [danwritecode](https://github.com/danwritecode/clings/issues?q=is%3Aissue+is%3Aopen+author%3Adanwritecode)
https://github.com/danwritecode/clings/issues/137 [help wanted](https://github.com/danwritecode/clings/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22)
#137 opened 2 days ago by [danwritecode](https://github.com/danwritecode/clings/issues?q=is%3Aissue+is%3Aopen+author%3Adanwritecode)
https://github.com/danwritecode/clings/issues/136 [help wanted](https://github.com/danwritecode/clings/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22)
#136 opened 2 days ago by [danwritecode](https://github.com/danwritecode/clings/issues?q=is%3Aissue+is%3Aopen+author%3Adanwritecode)
https://github.com/danwritecode/clings/issues/135 [help wanted](https://github.com/danwritecode/clings/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22)
#135 opened 2 days ago by [danwritecode](https://github.com/danwritecode/clings/issues?q=is%3Aissue+is%3Aopen+author%3Adanwritecode)
https://github.com/danwritecode/clings/issues/134 [help wanted](https://github.com/danwritecode/clings/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22)
#134 opened 2 days ago by [danwritecode](https://github.com/danwritecode/clings/issues?q=is%3Aissue+is%3Aopen+author%3Adanwritecode)
https://github.com/danwritecode/clings/issues/133 [help wanted](https://github.com/danwritecode/clings/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22)

**Comment by danwritecode** [comment]
I was able to add you to this one, but need to add you as a collaborator so i can add you to others. sent you the request.

**Comment by 7etsuo** [comment]
Got it thanks!
