### ISSUE TITLE
Refactor main.c to Improve Organization by Segregating Display Functions

### ISSUE THREAD

**Issue by 7etsuo** [danwritecode/clings#150]
To enhance the readability and maintainability of main.c, possibly reorganize the display-related code. Specifically, the function prototypes and their definitions could be moved to dedicated files. This involves:

1. Creating a new header file display.h to contain all display-related prototypes:

```c
#ifndef DISPLAY_H
#define DISPLAY_H

... 

void display(Exercise *exercise, ExecutionState *state, DisplayMode display_mode);
void display_debug(Exercise *exercise);
void display_failure(Exercise *exercise, ExecutionState *state);
void display_success();
void display_marked_incomplete(Exercise *exercise, ExecutionState *state); 
...

#endif // DISPLAY_H
```

2. Implementing the above functions in a new source file display.c. This will clean up main.c and modularize the code, making it easier to manage.

Also, some of the structs will need to be forward declarations in display.h to avoid collisions.

**Comment by danwritecode** [comment]
you read my mind, i was going to move these to a header file. Will work on it this weekend.
